version: '3.8'

services:

  rating-teams-db:
    container_name: rating-teams-db
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: raiting_team_events
      PGPORT: 3003
    ports:
      - "3003:3003"
    volumes:
      - "./db/psql_protected:/var/lib/postgresql/data/"
      - "./db/psql_backup.sql:/docker-entrypoint-initdb.d/01-dump.sql"
      - "./db/restore-db.sh:/docker-entrypoint-initdb.d/02-restore-db.sh"
    networks:
      - be

  rating-teams-be:
    container_name: rating-teams-be
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    networks:
      - be
      - fe

  rating-teams-fe:
    container_name: rating-teams-fe
    env_file:
      - ./client/.env
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - VITE_PUBLIC_HOST=localhost
    depends_on:
      - rating-teams-be
    networks:
      - fe

networks:
  fe:
    driver: bridge
  be:
    driver: bridge  

