
###
# USERS--------------------------------------------------------
###
# USERS--------------------------------------------------------
# get all users from specific team
GET http://localhost:3000/api/users?limit=4&email=mail




###
# EVENTS--------------------------------------------------------
GET http://localhost:3000/api/events?direction=Научная деятельность

#  GET http://localhost:3000/api/events?dateStart=2023-04-26&dateEnd=2024-01-26





###
# TEAMS--------------------------------------------------------
# TEAMS--------------------------------------------------------
# get all users from specific team
GET http://localhost:3000/api/teams/direction?id_parent=3

###
# get team by id
GET http://localhost:3000/api/teams/?id_parent=3

###
# select head user and teams
GET http://localhost:3000/api/teams

###
# create new team
POST http://localhost:3000/api/teams HTTP/1.1
content-type: application/json

{
    "userID":1,
    "shortname": "dddd2",
    "description": "Хотим подняться на гору",
    "title":"hddddhh"
}






###
# student-------------------------------------------------------
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "studnumber": "9",
    "fullname": "psmsokmgoksmbk",
    "email": "string",
    "education_group": "string",  
    "institute": "string",
    "gender": "string" ,
    "phone": "string",
    "birthdate": "24-07-2001",
    "type_time_study": "string",
    "permissions":[]
}





###
# functions------------------------------------------------------

//create new
POST http://localhost:3000/api/users/functions HTTP/1.1
content-type: application/json

{
    "title": "shit",
    "team": "45"
   
}







###
# user functions------------------------------------------------

//create new
POST http://localhost:3000/api/users/userFunctions HTTP/1.1
content-type: application/json

{
    "user": "300",
    "function": "21"
   
}

###
# login
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "password":123,
    "email": "admin@mail.ru",
}




