GET http://localhost:3000/api/users/1



###
# TEAMS
# get all users from specific team
GET http://localhost:3000/api/teams/with_users/2

###
# get team by id
GET http://localhost:3000/api/teams/2

###

# select head user and teams
GET http://localhost:3000/api/teams
# find users by specific role
# GET http://localhost:3000/api/users/role/supervisor

###

//find teams with cpecific position user
GET http://localhost:3000/api/teams/user_role/руководитель


###

//get directions
GET http://localhost:3000/api/teams/directions


