###
# student-------------------------------------------------------
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
  "studnumber": "9",
  "fullname": "psmsokmgoksmbk",
  "email": "string",
  "education_group": "string",
  "institute": "string",
  "gender": "string",
  "phone": "string",
  "birthdate": "24-07-2001",
  "type_time_study": "string",
  "permissions": []
}


###
# functions------------------------------------------------------

//create new
POST http://localhost:3000/api/users/functions HTTP/1.1
content-type: application/json

{
  "title": "shit2",
  "team": 31
}

###
DELETE  http://localhost:3000/api/users/team/17/leader/54 HTTP/1.1



###
PUT http://localhost:3000/api/users/functions/59 HTTP/1.1
content-type: application/json

{
  "title": "shit4",
  "team": 30
}





###
# user functions------------------------------------------------

//create new
POST http://localhost:3000/api/users/userFunctions HTTP/1.1
content-type: application/json

{
  "user": "300",
  "function": "21"
}


### general
# DICTIONARY
GET http://localhost:3000/api/general/dictionary/2

### mail
POST http://localhost:3000/api/general/mail HTTP/1.1
content-type: application/json

{
  "to": "AkitaSpam@gmail.com"
}





###
GET http://localhost:3000/api/uploads/file_buffer?path=./public/media/6b3620e359194339a2bc2409fb8de569.png

# get excel file event direction REPORT
###
GET http://localhost:3000/api/uploads/excel/events_direction

###
GET http://localhost:3000/api/uploads/excel/events_of_team?teamId=1



###
# DELETE FILE
DELETE  http://localhost:3000/api/uploads HTTP/1.1
content-type: application/json

{
  "pathUrl": "http://localhost:3000/public/media/2023.06/16/1686917327458_3y9kiw0d17b9c073259231460d65043eb882ef.jpeg"
}







