
###
# USERS--------------------------------------------------------
###
# USERS--------------------------------------------------------
# get all users from specific team
GET http://localhost:3000/api/users?limit=4&email=mail




###
# EVENTS--------------------------------------------------------
GET http://localhost:3000/api/events?id=20

###
GET http://localhost:3000/api/events/5

### events_of_team
GET http://localhost:3000/api/events/events_of_team/7?level=
###
GET http://localhost:3000/api/events?limit=5&offset=0&dateStart=2018-08-17T02:27:52.713Z&dateEnd=2023-08-17T07:33:52.713Z

### update event
PUT  http://localhost:3000/api/events/20 HTTP/1.1
content-type: application/json

{
    "status":true
    
}


###
# journals
GET http://localhost:3000/api/events/journal
###
GET http://localhost:3000/api/events/external




###
# TEAMS--------------------------------------------------------
# TEAMS--------------------------------------------------------
# get all users from specific team
GET http://localhost:3000/api/teams/51

###
# get team by id
GET http://localhost:3000/api/teams?limit=4&offset=0

###
#directions
GET http://localhost:3000/api/teams/directions


###
# select head user and teams
GET http://localhost:3000/api/teams?limit=2&offset=3


###
PUT  http://localhost:3000/api/teams/37/change_archive HTTP/1.1
content-type: application/json

{
    "isArchive":true
    
}
###
# create new team
POST http://localhost:3000/api/teams HTTP/1.1
content-type: application/json

{
    "userID":4,
    "shortname": "dddd2",
    "description": "Хотим подняться на гору",
    "title":"hddddhh",
    "cabinet":"8",
    "id_parent":4
   
}

###
PUT http://localhost:3000/api/teams/17 HTTP/1.1
content-type: application/json

{
    "oldLeaderId":63,
    "newLeaderId":54,
    "shortname": "train1",
    "description": "Хотим подняться на гору",
    "title":"hddddhh",
    "document":"hddddhh",
    "charterTeam":"dddddd",
    "cabinet":"8"
   
}

###
# student-------------------------------------------------------
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "studnumber": "9",
    "fullname": "psmsokmgoksmbk",
    "email": "string",
    "education_group": "string",  
    "institute": "string",
    "gender": "string" ,
    "phone": "string",
    "birthdate": "24-07-2001",
    "type_time_study": "string",
    "permissions":[]
}





###
# functions------------------------------------------------------

//create new
POST http://localhost:3000/api/users/functions HTTP/1.1
content-type: application/json

{
    "title": "shit2",
    "team": 31
   
}

###
DELETE  http://localhost:3000/api/users/team/17/leader/54 HTTP/1.1

# update
###
PUT http://localhost:3000/api/users/functions/59 HTTP/1.1
content-type: application/json

{
    "title": "shit4",
    "team":30
}








###
# user functions------------------------------------------------

//create new
POST http://localhost:3000/api/users/userFunctions HTTP/1.1
content-type: application/json

{
    "user": "300",
    "function": "21"
   
}

###
# login
POST https://rating-teams-events.ovz1.j37315531.m1yvm.vps.myjino.ru/api/users/login HTTP/1.1
content-type: application/json

{
    "password":123,
    "username": "bossTeam"
}



### general
# DICTIONARY
GET http://localhost:3000/api/general/dictionary/2

### mail
POST http://localhost:3000/api/general/mail HTTP/1.1
content-type: application/json

{
    "to":"AkitaSpam@gmail.com"
}




# UPLOAD
###
GET http://localhost:3000/api/uploads/file_buffer?path=./public/media/6b3620e359194339a2bc2409fb8de569.png

# get excel file event direction REPORT
###
GET http://localhost:3000/api/uploads/excel/events_direction

###
GET http://localhost:3000/api/uploads/excel/events_of_team?teamId=1

###
GET http://localhost:3000/api/teams/59/requisition?user_id=3



###
# DELETE FILE
DELETE  http://localhost:3000/api/uploads HTTP/1.1
content-type: application/json

{
    "pathUrl":"http://localhost:3000/public/media/2023.06/16/1686917327458_3y9kiw0d17b9c073259231460d65043eb882ef.jpeg"
}




# forms
### get requisition
GET http://localhost:3000/api/forms/requisition/6



